### ISSUE TITLE
Error- Input must be integer

### ISSUE THREAD

**Issue by gkbal** [piScope/piScope#56]
While trying to run the solve (serial) feature locally on the machine in Pertra-m, i get the following error below. Could you please advice on how I can resolve this error?

My project file is located at -
home/gurleenkbal/Documents/Petram_SSRFantenna/SSRFantennaTom3.pfz

Failed to during pre-processing model data
Traceback (most recent call last):
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PetraM_Base-0.9.1-py3.6.egg/petram/mfem_viewer.py", line 916, in onSerDriver
    self.run_preprocess()
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PetraM_Base-0.9.1-py3.6.egg/petram/mfem_viewer.py", line 1456, in run_preprocess
    engine.run_preprocess(model.namespaces, model.datasets)
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PetraM_Base-0.9.1-py3.6.egg/petram/engine.py", line 406, in run_preprocess
    node.preprocess_params(self)
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PetraM_RF-0.9.1-py3.6.egg/petram/phys/em3d/em3d_port.py", line 369, in preprocess_params
    vv = np.vstack([mesh.GetVertexArray(i) for i in ivert])
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PetraM_RF-0.9.1-py3.6.egg/petram/phys/em3d/em3d_port.py", line 369, in <listcomp>
    vv = np.vstack([mesh.GetVertexArray(i) for i in ivert])
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PyMFEM-4.0.1-py3.6.egg/mfem/_ser/mesh.py", line 891, in GetVertexArray
    return _mesh.Mesh_GetVertexArray(self, i)
TypeError: Input must be integer

**Comment by sshiraiwa** [comment]
The model file looks to have multiple issues. The direct reason of this error is 
that the port boundary is set on a wrong surface. But, before fixing it, the geometry 
needs to be fixed. To run an RF simulation, you need to have a mesh representing 
the air, The geometry seems to have a metal geometry. We need to do some
boolean subtraction to form the air domain. 

It may be simpler to go through this with a zoom call. Please let me know when
you are available. Meantime, please take a look at a file in 

 /home/shiraiwa/piscope_projects/PetraM_example/lapd_mar2018.pfz
