### ISSUE TITLE
OSX python 3.9 or 3.10

### ISSUE THREAD

**Issue by bpduval** [piScope/piScope#85]
Tried to follow instructions on https://piscope.psfc.mit.edu/index.php/Installing_Petra-M and tried to install manually (no problem appeared with installation)- In both cases, when I try to run, I get a problem with : ValueError: '3dpath' is not a valid parameter name (I have no idea what 3dpath is/means)

Traceback (most recent call last):
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/piscope.py", line 29, in <module>
    from ifigure.ifigure_app import ifigure_app, MyApp
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/ifigure_app.py", line 22, in <module>
    import ifigure.server
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/server.py", line 35, in <module>
    import ifigure.events
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/events.py", line 18, in <module>
    from ifigure.widgets.book_viewer import BookViewer
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/widgets/book_viewer.py", line 42, in <module>
    from ifigure.widgets.canvas.ifigure_canvas import ifigure_canvas
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/widgets/canvas/ifigure_canvas.py", line 55, in <module>
    from ifigure.widgets.navibar2 import navibar
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/widgets/navibar2.py", line 9, in <module>
    from ifigure.mto.fig_axes import FigInsetAxes
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/mto/fig_axes.py", line 39, in <module>
    from ifigure.mto.fig_plot import FigPlot
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/mto/fig_plot.py", line 25, in <module>
    from ifigure.matplotlib_mod.art3d_gl import Line3DCollectionGL, LineGL
  File "/usr/local/Cellar/twopi/1.1.7/src/piScope/python/ifigure/matplotlib_mod/art3d_gl.py", line 430, in <module>
    class AxesImageGL(ArtGL, AxesImage):
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 120, in __init_subclass__
    cls._update_set_signature_and_docstring()
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 140, in _update_set_signature_and_docstring
    *[Parameter(prop, Parameter.KEYWORD_ONLY, default=_UNSET)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/artist.py", line 140, in <listcomp>
    *[Parameter(prop, Parameter.KEYWORD_ONLY, default=_UNSET)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2666, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: '3dpath' is not a valid parameter name

**Comment by sshiraiwa** [comment]
This was due to the change matplotlib 3.5. Current master should work. 
I am experiences some issues with Matplotlib 3.6, which I am working on in mpl_36_support branch
